{
  parserClass="com.github.kumaraman21.intellijbehave.parser.StoryParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Story"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.kumaraman21.intellijbehave.psi"
  psiImplPackage="com.github.kumaraman21.intellijbehave.psi.impl"

  elementTypeHolderClass="com.github.kumaraman21.intellijbehave.parser.StoryTypes"
  elementTypeClass="com.github.kumaraman21.intellijbehave.parser.StoryElementType"
  tokenTypeClass="com.github.kumaraman21.intellijbehave.parser.StoryTokenType"
}

storyFile ::= (narrative scenario* | BAD_CHARACTER)
narrative ::= STORY_DESCRIPTION STORY_DESCRIPTION*
scenario ::= scenarioHeader (metaInfo | example | given | when | then | table | COMMENT)*
scenarioHeader ::= SCENARIO_TYPE SCENARIO_TEXT
metaInfo ::= META_TYPE META_KEY META_TEXT
example ::= EXAMPLE_TYPE EXAMPLE_TEXT
given ::= GIVEN_TYPE STEP_TEXT?
when ::= WHEN_TYPE STEP_TEXT?
then ::= THEN_TYPE STEP_TEXT?
table ::= TABLE_DELIM (TABLE_CELL TABLE_DELIM)+
